/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as Routes_rootRouteImport } from './routes/__root'
import { Route as UauthenticatedLayoutRouteImport } from './_uauthenticatedLayout'
import { Route as AuthenticatedLayoutRouteImport } from './_authenticatedLayout'
import { Route as AuthenticatedLayoutIndexRouteImport } from './_authenticatedLayout/index'
import { Route as ReportUserRouteImport } from './report/$user'
import { Route as UauthenticatedLayoutLoginIndexRouteImport } from './_uauthenticatedLayout/login/index'
import { Route as AuthenticatedLayoutTestimonialsIndexRouteImport } from './_authenticatedLayout/testimonials/index'
import { Route as AuthenticatedLayoutQuizzesIndexRouteImport } from './_authenticatedLayout/quizzes/index'
import { Route as AuthenticatedLayoutProgramsIndexRouteImport } from './_authenticatedLayout/programs/index'
import { Route as AuthenticatedLayoutPageSettingsIndexRouteImport } from './_authenticatedLayout/page-settings/index'
import { Route as AuthenticatedLayoutMeetingSessionsIndexRouteImport } from './_authenticatedLayout/meeting-sessions/index'
import { Route as AuthenticatedLayoutClassesIndexRouteImport } from './_authenticatedLayout/classes/index'
import { Route as AuthenticatedLayoutArticlesIndexRouteImport } from './_authenticatedLayout/articles/index'
import { Route as AuthenticatedLayoutUsersStudentsRouteImport } from './_authenticatedLayout/users/students'
import { Route as AuthenticatedLayoutUsersMentorsRouteImport } from './_authenticatedLayout/users/mentors'
import { Route as AuthenticatedLayoutUsersDeletedRouteImport } from './_authenticatedLayout/users/deleted'
import { Route as AuthenticatedLayoutQuizzesQuizIdRouteImport } from './_authenticatedLayout/quizzes/$quizId'
import { Route as AuthenticatedLayoutMeetingSessionsUserRouteImport } from './_authenticatedLayout/meeting-sessions/$user'

const Routes_rootRoute = Routes_rootRouteImport.update({
  id: '/routes/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const UauthenticatedLayoutRoute = UauthenticatedLayoutRouteImport.update({
  id: '/_uauthenticatedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticatedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const ReportUserRoute = ReportUserRouteImport.update({
  id: '/report/$user',
  path: '/report/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const UauthenticatedLayoutLoginIndexRoute =
  UauthenticatedLayoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => UauthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutTestimonialsIndexRoute =
  AuthenticatedLayoutTestimonialsIndexRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutQuizzesIndexRoute =
  AuthenticatedLayoutQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutProgramsIndexRoute =
  AuthenticatedLayoutProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutPageSettingsIndexRoute =
  AuthenticatedLayoutPageSettingsIndexRouteImport.update({
    id: '/page-settings/',
    path: '/page-settings/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMeetingSessionsIndexRoute =
  AuthenticatedLayoutMeetingSessionsIndexRouteImport.update({
    id: '/meeting-sessions/',
    path: '/meeting-sessions/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutClassesIndexRoute =
  AuthenticatedLayoutClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutArticlesIndexRoute =
  AuthenticatedLayoutArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutUsersStudentsRoute =
  AuthenticatedLayoutUsersStudentsRouteImport.update({
    id: '/users/students',
    path: '/users/students',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutUsersMentorsRoute =
  AuthenticatedLayoutUsersMentorsRouteImport.update({
    id: '/users/mentors',
    path: '/users/mentors',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutUsersDeletedRoute =
  AuthenticatedLayoutUsersDeletedRouteImport.update({
    id: '/users/deleted',
    path: '/users/deleted',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutQuizzesQuizIdRoute =
  AuthenticatedLayoutQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMeetingSessionsUserRoute =
  AuthenticatedLayoutMeetingSessionsUserRouteImport.update({
    id: '/meeting-sessions/$user',
    path: '/meeting-sessions/$user',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/report/$user': typeof ReportUserRoute
  '/routes': typeof Routes_rootRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/meeting-sessions/$user': typeof AuthenticatedLayoutMeetingSessionsUserRoute
  '/quizzes/$quizId': typeof AuthenticatedLayoutQuizzesQuizIdRoute
  '/users/deleted': typeof AuthenticatedLayoutUsersDeletedRoute
  '/users/mentors': typeof AuthenticatedLayoutUsersMentorsRoute
  '/users/students': typeof AuthenticatedLayoutUsersStudentsRoute
  '/articles': typeof AuthenticatedLayoutArticlesIndexRoute
  '/classes': typeof AuthenticatedLayoutClassesIndexRoute
  '/meeting-sessions': typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  '/page-settings': typeof AuthenticatedLayoutPageSettingsIndexRoute
  '/programs': typeof AuthenticatedLayoutProgramsIndexRoute
  '/quizzes': typeof AuthenticatedLayoutQuizzesIndexRoute
  '/testimonials': typeof AuthenticatedLayoutTestimonialsIndexRoute
  '/login': typeof UauthenticatedLayoutLoginIndexRoute
}
export interface FileRoutesByTo {
  '/report/$user': typeof ReportUserRoute
  '/routes': typeof Routes_rootRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/meeting-sessions/$user': typeof AuthenticatedLayoutMeetingSessionsUserRoute
  '/quizzes/$quizId': typeof AuthenticatedLayoutQuizzesQuizIdRoute
  '/users/deleted': typeof AuthenticatedLayoutUsersDeletedRoute
  '/users/mentors': typeof AuthenticatedLayoutUsersMentorsRoute
  '/users/students': typeof AuthenticatedLayoutUsersStudentsRoute
  '/articles': typeof AuthenticatedLayoutArticlesIndexRoute
  '/classes': typeof AuthenticatedLayoutClassesIndexRoute
  '/meeting-sessions': typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  '/page-settings': typeof AuthenticatedLayoutPageSettingsIndexRoute
  '/programs': typeof AuthenticatedLayoutProgramsIndexRoute
  '/quizzes': typeof AuthenticatedLayoutQuizzesIndexRoute
  '/testimonials': typeof AuthenticatedLayoutTestimonialsIndexRoute
  '/login': typeof UauthenticatedLayoutLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticatedLayout': typeof AuthenticatedLayoutRouteWithChildren
  '/_uauthenticatedLayout': typeof UauthenticatedLayoutRouteWithChildren
  '/report/$user': typeof ReportUserRoute
  '/routes/__root': typeof Routes_rootRoute
  '/_authenticatedLayout/': typeof AuthenticatedLayoutIndexRoute
  '/_authenticatedLayout/meeting-sessions/$user': typeof AuthenticatedLayoutMeetingSessionsUserRoute
  '/_authenticatedLayout/quizzes/$quizId': typeof AuthenticatedLayoutQuizzesQuizIdRoute
  '/_authenticatedLayout/users/deleted': typeof AuthenticatedLayoutUsersDeletedRoute
  '/_authenticatedLayout/users/mentors': typeof AuthenticatedLayoutUsersMentorsRoute
  '/_authenticatedLayout/users/students': typeof AuthenticatedLayoutUsersStudentsRoute
  '/_authenticatedLayout/articles/': typeof AuthenticatedLayoutArticlesIndexRoute
  '/_authenticatedLayout/classes/': typeof AuthenticatedLayoutClassesIndexRoute
  '/_authenticatedLayout/meeting-sessions/': typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  '/_authenticatedLayout/page-settings/': typeof AuthenticatedLayoutPageSettingsIndexRoute
  '/_authenticatedLayout/programs/': typeof AuthenticatedLayoutProgramsIndexRoute
  '/_authenticatedLayout/quizzes/': typeof AuthenticatedLayoutQuizzesIndexRoute
  '/_authenticatedLayout/testimonials/': typeof AuthenticatedLayoutTestimonialsIndexRoute
  '/_uauthenticatedLayout/login/': typeof UauthenticatedLayoutLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/report/$user'
    | '/routes'
    | '/'
    | '/meeting-sessions/$user'
    | '/quizzes/$quizId'
    | '/users/deleted'
    | '/users/mentors'
    | '/users/students'
    | '/articles'
    | '/classes'
    | '/meeting-sessions'
    | '/page-settings'
    | '/programs'
    | '/quizzes'
    | '/testimonials'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/report/$user'
    | '/routes'
    | '/'
    | '/meeting-sessions/$user'
    | '/quizzes/$quizId'
    | '/users/deleted'
    | '/users/mentors'
    | '/users/students'
    | '/articles'
    | '/classes'
    | '/meeting-sessions'
    | '/page-settings'
    | '/programs'
    | '/quizzes'
    | '/testimonials'
    | '/login'
  id:
    | '__root__'
    | '/_authenticatedLayout'
    | '/_uauthenticatedLayout'
    | '/report/$user'
    | '/routes/__root'
    | '/_authenticatedLayout/'
    | '/_authenticatedLayout/meeting-sessions/$user'
    | '/_authenticatedLayout/quizzes/$quizId'
    | '/_authenticatedLayout/users/deleted'
    | '/_authenticatedLayout/users/mentors'
    | '/_authenticatedLayout/users/students'
    | '/_authenticatedLayout/articles/'
    | '/_authenticatedLayout/classes/'
    | '/_authenticatedLayout/meeting-sessions/'
    | '/_authenticatedLayout/page-settings/'
    | '/_authenticatedLayout/programs/'
    | '/_authenticatedLayout/quizzes/'
    | '/_authenticatedLayout/testimonials/'
    | '/_uauthenticatedLayout/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  UauthenticatedLayoutRoute: typeof UauthenticatedLayoutRouteWithChildren
  ReportUserRoute: typeof ReportUserRoute
  Routes_rootRoute: typeof Routes_rootRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routes/__root': {
      id: '/routes/__root'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof Routes_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_uauthenticatedLayout': {
      id: '/_uauthenticatedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticatedLayout': {
      id: '/_authenticatedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticatedLayout/': {
      id: '/_authenticatedLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/report/$user': {
      id: '/report/$user'
      path: '/report/$user'
      fullPath: '/report/$user'
      preLoaderRoute: typeof ReportUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_uauthenticatedLayout/login/': {
      id: '/_uauthenticatedLayout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UauthenticatedLayoutLoginIndexRouteImport
      parentRoute: typeof UauthenticatedLayoutRoute
    }
    '/_authenticatedLayout/testimonials/': {
      id: '/_authenticatedLayout/testimonials/'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof AuthenticatedLayoutTestimonialsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/quizzes/': {
      id: '/_authenticatedLayout/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AuthenticatedLayoutQuizzesIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/programs/': {
      id: '/_authenticatedLayout/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthenticatedLayoutProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/page-settings/': {
      id: '/_authenticatedLayout/page-settings/'
      path: '/page-settings'
      fullPath: '/page-settings'
      preLoaderRoute: typeof AuthenticatedLayoutPageSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/meeting-sessions/': {
      id: '/_authenticatedLayout/meeting-sessions/'
      path: '/meeting-sessions'
      fullPath: '/meeting-sessions'
      preLoaderRoute: typeof AuthenticatedLayoutMeetingSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/classes/': {
      id: '/_authenticatedLayout/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedLayoutClassesIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/articles/': {
      id: '/_authenticatedLayout/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedLayoutArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/users/students': {
      id: '/_authenticatedLayout/users/students'
      path: '/users/students'
      fullPath: '/users/students'
      preLoaderRoute: typeof AuthenticatedLayoutUsersStudentsRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/users/mentors': {
      id: '/_authenticatedLayout/users/mentors'
      path: '/users/mentors'
      fullPath: '/users/mentors'
      preLoaderRoute: typeof AuthenticatedLayoutUsersMentorsRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/users/deleted': {
      id: '/_authenticatedLayout/users/deleted'
      path: '/users/deleted'
      fullPath: '/users/deleted'
      preLoaderRoute: typeof AuthenticatedLayoutUsersDeletedRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/quizzes/$quizId': {
      id: '/_authenticatedLayout/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedLayoutQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/meeting-sessions/$user': {
      id: '/_authenticatedLayout/meeting-sessions/$user'
      path: '/meeting-sessions/$user'
      fullPath: '/meeting-sessions/$user'
      preLoaderRoute: typeof AuthenticatedLayoutMeetingSessionsUserRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
  AuthenticatedLayoutMeetingSessionsUserRoute: typeof AuthenticatedLayoutMeetingSessionsUserRoute
  AuthenticatedLayoutQuizzesQuizIdRoute: typeof AuthenticatedLayoutQuizzesQuizIdRoute
  AuthenticatedLayoutUsersDeletedRoute: typeof AuthenticatedLayoutUsersDeletedRoute
  AuthenticatedLayoutUsersMentorsRoute: typeof AuthenticatedLayoutUsersMentorsRoute
  AuthenticatedLayoutUsersStudentsRoute: typeof AuthenticatedLayoutUsersStudentsRoute
  AuthenticatedLayoutArticlesIndexRoute: typeof AuthenticatedLayoutArticlesIndexRoute
  AuthenticatedLayoutClassesIndexRoute: typeof AuthenticatedLayoutClassesIndexRoute
  AuthenticatedLayoutMeetingSessionsIndexRoute: typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  AuthenticatedLayoutPageSettingsIndexRoute: typeof AuthenticatedLayoutPageSettingsIndexRoute
  AuthenticatedLayoutProgramsIndexRoute: typeof AuthenticatedLayoutProgramsIndexRoute
  AuthenticatedLayoutQuizzesIndexRoute: typeof AuthenticatedLayoutQuizzesIndexRoute
  AuthenticatedLayoutTestimonialsIndexRoute: typeof AuthenticatedLayoutTestimonialsIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
  AuthenticatedLayoutMeetingSessionsUserRoute:
    AuthenticatedLayoutMeetingSessionsUserRoute,
  AuthenticatedLayoutQuizzesQuizIdRoute: AuthenticatedLayoutQuizzesQuizIdRoute,
  AuthenticatedLayoutUsersDeletedRoute: AuthenticatedLayoutUsersDeletedRoute,
  AuthenticatedLayoutUsersMentorsRoute: AuthenticatedLayoutUsersMentorsRoute,
  AuthenticatedLayoutUsersStudentsRoute: AuthenticatedLayoutUsersStudentsRoute,
  AuthenticatedLayoutArticlesIndexRoute: AuthenticatedLayoutArticlesIndexRoute,
  AuthenticatedLayoutClassesIndexRoute: AuthenticatedLayoutClassesIndexRoute,
  AuthenticatedLayoutMeetingSessionsIndexRoute:
    AuthenticatedLayoutMeetingSessionsIndexRoute,
  AuthenticatedLayoutPageSettingsIndexRoute:
    AuthenticatedLayoutPageSettingsIndexRoute,
  AuthenticatedLayoutProgramsIndexRoute: AuthenticatedLayoutProgramsIndexRoute,
  AuthenticatedLayoutQuizzesIndexRoute: AuthenticatedLayoutQuizzesIndexRoute,
  AuthenticatedLayoutTestimonialsIndexRoute:
    AuthenticatedLayoutTestimonialsIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface UauthenticatedLayoutRouteChildren {
  UauthenticatedLayoutLoginIndexRoute: typeof UauthenticatedLayoutLoginIndexRoute
}

const UauthenticatedLayoutRouteChildren: UauthenticatedLayoutRouteChildren = {
  UauthenticatedLayoutLoginIndexRoute: UauthenticatedLayoutLoginIndexRoute,
}

const UauthenticatedLayoutRouteWithChildren =
  UauthenticatedLayoutRoute._addFileChildren(UauthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  UauthenticatedLayoutRoute: UauthenticatedLayoutRouteWithChildren,
  ReportUserRoute: ReportUserRoute,
  Routes_rootRoute: Routes_rootRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
