/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as Routes_rootRouteImport } from './routes/__root'
import { Route as UauthenticatedLayoutRouteImport } from './_uauthenticatedLayout'
import { Route as AuthenticatedLayoutRouteImport } from './_authenticatedLayout'
import { Route as AuthenticatedLayoutIndexRouteImport } from './_authenticatedLayout/index'
import { Route as UauthenticatedLayoutLoginIndexRouteImport } from './_uauthenticatedLayout/login/index'
import { Route as AuthenticatedLayoutUsersIndexRouteImport } from './_authenticatedLayout/users/index'
import { Route as AuthenticatedLayoutPageSettingsIndexRouteImport } from './_authenticatedLayout/page-settings/index'
import { Route as AuthenticatedLayoutMeetingSessionsIndexRouteImport } from './_authenticatedLayout/meeting-sessions/index'
import { Route as AuthenticatedLayoutClassesIndexRouteImport } from './_authenticatedLayout/classes/index'
import { Route as AuthenticatedLayoutArticlesIndexRouteImport } from './_authenticatedLayout/articles/index'
import { Route as AuthenticatedLayoutMeetingSessionsUserRouteImport } from './_authenticatedLayout/meeting-sessions/$user'

const Routes_rootRoute = Routes_rootRouteImport.update({
  id: '/routes/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const UauthenticatedLayoutRoute = UauthenticatedLayoutRouteImport.update({
  id: '/_uauthenticatedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticatedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const UauthenticatedLayoutLoginIndexRoute =
  UauthenticatedLayoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => UauthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutUsersIndexRoute =
  AuthenticatedLayoutUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutPageSettingsIndexRoute =
  AuthenticatedLayoutPageSettingsIndexRouteImport.update({
    id: '/page-settings/',
    path: '/page-settings/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMeetingSessionsIndexRoute =
  AuthenticatedLayoutMeetingSessionsIndexRouteImport.update({
    id: '/meeting-sessions/',
    path: '/meeting-sessions/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutClassesIndexRoute =
  AuthenticatedLayoutClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutArticlesIndexRoute =
  AuthenticatedLayoutArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMeetingSessionsUserRoute =
  AuthenticatedLayoutMeetingSessionsUserRouteImport.update({
    id: '/meeting-sessions/$user',
    path: '/meeting-sessions/$user',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/routes': typeof Routes_rootRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/meeting-sessions/$user': typeof AuthenticatedLayoutMeetingSessionsUserRoute
  '/articles': typeof AuthenticatedLayoutArticlesIndexRoute
  '/classes': typeof AuthenticatedLayoutClassesIndexRoute
  '/meeting-sessions': typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  '/page-settings': typeof AuthenticatedLayoutPageSettingsIndexRoute
  '/users': typeof AuthenticatedLayoutUsersIndexRoute
  '/login': typeof UauthenticatedLayoutLoginIndexRoute
}
export interface FileRoutesByTo {
  '/routes': typeof Routes_rootRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/meeting-sessions/$user': typeof AuthenticatedLayoutMeetingSessionsUserRoute
  '/articles': typeof AuthenticatedLayoutArticlesIndexRoute
  '/classes': typeof AuthenticatedLayoutClassesIndexRoute
  '/meeting-sessions': typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  '/page-settings': typeof AuthenticatedLayoutPageSettingsIndexRoute
  '/users': typeof AuthenticatedLayoutUsersIndexRoute
  '/login': typeof UauthenticatedLayoutLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticatedLayout': typeof AuthenticatedLayoutRouteWithChildren
  '/_uauthenticatedLayout': typeof UauthenticatedLayoutRouteWithChildren
  '/routes/__root': typeof Routes_rootRoute
  '/_authenticatedLayout/': typeof AuthenticatedLayoutIndexRoute
  '/_authenticatedLayout/meeting-sessions/$user': typeof AuthenticatedLayoutMeetingSessionsUserRoute
  '/_authenticatedLayout/articles/': typeof AuthenticatedLayoutArticlesIndexRoute
  '/_authenticatedLayout/classes/': typeof AuthenticatedLayoutClassesIndexRoute
  '/_authenticatedLayout/meeting-sessions/': typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  '/_authenticatedLayout/page-settings/': typeof AuthenticatedLayoutPageSettingsIndexRoute
  '/_authenticatedLayout/users/': typeof AuthenticatedLayoutUsersIndexRoute
  '/_uauthenticatedLayout/login/': typeof UauthenticatedLayoutLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/routes'
    | '/'
    | '/meeting-sessions/$user'
    | '/articles'
    | '/classes'
    | '/meeting-sessions'
    | '/page-settings'
    | '/users'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/routes'
    | '/'
    | '/meeting-sessions/$user'
    | '/articles'
    | '/classes'
    | '/meeting-sessions'
    | '/page-settings'
    | '/users'
    | '/login'
  id:
    | '__root__'
    | '/_authenticatedLayout'
    | '/_uauthenticatedLayout'
    | '/routes/__root'
    | '/_authenticatedLayout/'
    | '/_authenticatedLayout/meeting-sessions/$user'
    | '/_authenticatedLayout/articles/'
    | '/_authenticatedLayout/classes/'
    | '/_authenticatedLayout/meeting-sessions/'
    | '/_authenticatedLayout/page-settings/'
    | '/_authenticatedLayout/users/'
    | '/_uauthenticatedLayout/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  UauthenticatedLayoutRoute: typeof UauthenticatedLayoutRouteWithChildren
  Routes_rootRoute: typeof Routes_rootRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routes/__root': {
      id: '/routes/__root'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof Routes_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_uauthenticatedLayout': {
      id: '/_uauthenticatedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UauthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticatedLayout': {
      id: '/_authenticatedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticatedLayout/': {
      id: '/_authenticatedLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_uauthenticatedLayout/login/': {
      id: '/_uauthenticatedLayout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UauthenticatedLayoutLoginIndexRouteImport
      parentRoute: typeof UauthenticatedLayoutRoute
    }
    '/_authenticatedLayout/users/': {
      id: '/_authenticatedLayout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedLayoutUsersIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/page-settings/': {
      id: '/_authenticatedLayout/page-settings/'
      path: '/page-settings'
      fullPath: '/page-settings'
      preLoaderRoute: typeof AuthenticatedLayoutPageSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/meeting-sessions/': {
      id: '/_authenticatedLayout/meeting-sessions/'
      path: '/meeting-sessions'
      fullPath: '/meeting-sessions'
      preLoaderRoute: typeof AuthenticatedLayoutMeetingSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/classes/': {
      id: '/_authenticatedLayout/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedLayoutClassesIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/articles/': {
      id: '/_authenticatedLayout/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthenticatedLayoutArticlesIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticatedLayout/meeting-sessions/$user': {
      id: '/_authenticatedLayout/meeting-sessions/$user'
      path: '/meeting-sessions/$user'
      fullPath: '/meeting-sessions/$user'
      preLoaderRoute: typeof AuthenticatedLayoutMeetingSessionsUserRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
  AuthenticatedLayoutMeetingSessionsUserRoute: typeof AuthenticatedLayoutMeetingSessionsUserRoute
  AuthenticatedLayoutArticlesIndexRoute: typeof AuthenticatedLayoutArticlesIndexRoute
  AuthenticatedLayoutClassesIndexRoute: typeof AuthenticatedLayoutClassesIndexRoute
  AuthenticatedLayoutMeetingSessionsIndexRoute: typeof AuthenticatedLayoutMeetingSessionsIndexRoute
  AuthenticatedLayoutPageSettingsIndexRoute: typeof AuthenticatedLayoutPageSettingsIndexRoute
  AuthenticatedLayoutUsersIndexRoute: typeof AuthenticatedLayoutUsersIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
  AuthenticatedLayoutMeetingSessionsUserRoute:
    AuthenticatedLayoutMeetingSessionsUserRoute,
  AuthenticatedLayoutArticlesIndexRoute: AuthenticatedLayoutArticlesIndexRoute,
  AuthenticatedLayoutClassesIndexRoute: AuthenticatedLayoutClassesIndexRoute,
  AuthenticatedLayoutMeetingSessionsIndexRoute:
    AuthenticatedLayoutMeetingSessionsIndexRoute,
  AuthenticatedLayoutPageSettingsIndexRoute:
    AuthenticatedLayoutPageSettingsIndexRoute,
  AuthenticatedLayoutUsersIndexRoute: AuthenticatedLayoutUsersIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface UauthenticatedLayoutRouteChildren {
  UauthenticatedLayoutLoginIndexRoute: typeof UauthenticatedLayoutLoginIndexRoute
}

const UauthenticatedLayoutRouteChildren: UauthenticatedLayoutRouteChildren = {
  UauthenticatedLayoutLoginIndexRoute: UauthenticatedLayoutLoginIndexRoute,
}

const UauthenticatedLayoutRouteWithChildren =
  UauthenticatedLayoutRoute._addFileChildren(UauthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  UauthenticatedLayoutRoute: UauthenticatedLayoutRouteWithChildren,
  Routes_rootRoute: Routes_rootRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
